//@version=5
indicator("Tuspe Special Mix", shorttitle="Tuspe", overlay=true)

//-----------------------------------------------------------------------------
// Input settings
//-----------------------------------------------------------------------------
show_pdhl = input(true, "Show Previous Day High/Low", group = "Highs & Lows")

// Moving Averages Lengths
ma_type = input.string("EMA", "MA Type", options = ["SMA", "EMA"], group = "Moving Averages")
fast_length = input.int(20, "Fast MA Length", group = "Moving Averages")
medium_length = input.int(50, "Medium MA Length", group = "Moving Averages")
slow_length = input.int(200, "Slow MA Length", group = "Moving Averages")

//-----------------------------------------------------------------------------
// Functions
//-----------------------------------------------------------------------------
hl() => [high, low]

phl(h, l, tf, css)=>
    var line high_line = line.new(na, na, na, na, xloc = xloc.bar_time, color = css, style = line.style_solid)
    var label high_lbl = label.new(na, na, xloc = xloc.bar_time, text = str.format('P{0}H', tf), color = color.new(color.white, 100), textcolor = css, size = size.small, style = label.style_label_left)
    var line low_line = line.new(na, na, na, na, xloc = xloc.bar_time, color = css, style = line.style_solid)
    var label low_lbl = label.new(na, na, xloc = xloc.bar_time, text = str.format('P{0}L', tf), color = color.new(color.white, 100), textcolor = css, size = size.small, style = label.style_label_left)

    hy = ta.valuewhen(h != h[1], h, 1)
    hx = ta.valuewhen(h == high, time, 1)

    ly = ta.valuewhen(l != l[1], l, 1)
    lx = ta.valuewhen(l == low, time, 1)

    if barstate.islast
        ext = time + (time - time[1]) * 20

        // High
        line.set_xy1(high_line, hx, hy)
        line.set_xy2(high_line, ext, hy)
        label.set_xy(high_lbl, ext, hy)

        // Low
        line.set_xy1(low_line, lx, ly)
        line.set_xy2(low_line, ext, ly)
        label.set_xy(low_lbl, ext, ly)

//-----------------------------------------------------------------------------
// Previous day high/low
//-----------------------------------------------------------------------------
[pdh, pdl] = request.security(syminfo.tickerid, 'D', hl(), lookahead = barmerge.lookahead_on)

pdhl_css = input.color(color.new(color.green, 40), "Previous Day Line Color", group = "Style")

// Fetch high and low for the previous day
var float prev_day_high = na
var float prev_day_low = na

if (dayofweek(time) != dayofweek(time[1]))
    prev_day_high := pdh
    prev_day_low := pdl

// Display Daily
if show_pdhl
    phl(prev_day_high, prev_day_low, 'D', pdhl_css)

// Alert for Previous Day High/Low
alertcondition(close > prev_day_high or close < prev_day_low, "Price Breaks Previous Day High/Low", "Price has broken the previous day's high or low.")

//-----------------------------------------------------------------------------
// Moving Averages
//-----------------------------------------------------------------------------
ma(src, length, type) =>
    if type == "SMA"
        ta.sma(src, length)
    else
        ta.ema(src, length)

fast_ma = ma(close, fast_length, ma_type)
medium_ma = ma(close, medium_length, ma_type)
slow_ma = ma(close, slow_length, ma_type)

plot(fast_ma, color=color.new(color.yellow, 0), linewidth=2, title="Fast MA")
plot(medium_ma, color=color.new(color.orange, 25), linewidth=1, title="Medium MA")
plot(slow_ma, color=color.new(#add8e6, 25), linewidth=3, title="Slow MA")

//-----------------------------------------------------------------------------
// Inside Bar
//-----------------------------------------------------------------------------
is_inside_bar = (high < high[1]) and (low > low[1])

// Change bar color if it's an Inside Bar
barcolor(is_inside_bar ? color.new(color.orange, 0) : na)

// Alert for Inside Bar
alertcondition(is_inside_bar, title="Inside Bar Alert", message="New Inside Bar spotted")

// Trigger alert only at the close of the inside bar
if is_inside_bar and barstate.isconfirmed
    alert("New Inside Bar spotted", alert.freq_once_per_bar_close)